---
title: "Predicting Turbulence Simulations"
author: "Enzo Moraes Mescall, Martin Olarte, Charlotte Coudert"
date: "2022-10-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Report should be no more than 4 pages
```


```{r libraries, echo = FALSE, results = FALSE, message = FALSE}
library(tidyverse)
```

```{r data}
data.train = read.csv("data-train.csv")
data.test = read.csv("data-test.csv")
```


## Introduction


## Methodology

We started off by creating a function that would take in a tuple of St, Re, and Fr and then return the four predicted moments. We did this using variable names that we were yet to define

```{r}
# temp models
model_m1 = lm(R_moment_1 ~ Re + Fr + St, data = clean)
model_m2 = lm(R_moment_2 ~ Re + Fr + St, data = clean)
model_m3 = lm(R_moment_3 ~ Re + Fr + St, data = clean)
model_m4 = lm(R_moment_4 ~ Re + Fr + St, data = clean)

predictive_model = function(test_St, test_Re, test_Fr) {
  newdata = data.frame(list(St = test_St, Re = as.factor(test_Re), Fr = as.factor(test_Fr)))
  
  m1 = predict(model_m1, newdata =  newdata)
  m2 = predict(model_m2, newdata =  newdata)
  m3 = predict(model_m3, newdata =  newdata)
  m4 = predict(model_m4, newdata =  newdata)
  
  return(c(m1, m2, m3, m4))
}
```


## Results


## Conclusion